### PR TITLE
Basic docs

### PR DESCRIPTION
**Pull request by cormullion**
I added an introductory section to the README.md on basic usage, and gave some structure to the document, and made some minor copy edits. I haven't added much in the way of new information.

### CODE REVIEW

**Comment by cormullion** [comment]
Ah, I see I've screwed up in github, because this PR also includes two files from pull request #97. Sorry.

**Comment by cormullion** [comment]
@jiahao no love for this PR then? :)

**Comment by jiahao** [comment]
It's not mergeable in its current stage. I just merged #97; you can rebase and try again.

**Comment by jiahao** [comment]
Also it would be nice to squash these commits.

**Pull request closed without merging**
