### PR TITLE
Fix RGB to HSL "L" conversion

### PR DESCRIPTION
**Pull request by rickhg12hs**
Referencing numerous RGB to HSL conversion algorithms (Google search hits, etc.), the min and max values need to be added, not subtracted.

### CODE REVIEW

**Comment by timholy** [comment]
Looks like the tests need to be updated?

**Comment by rickhg12hs** [comment]
I updated the tests, but need to admit that I only updated the values with the ones returned by Travis when the tests were failing.  I'm not qualified to assess the correctness of the tests or test results.

**Comment by timholy** [comment]
I'm a little suspicious that the tests with "hue" all have values between 0 and 1, but according to the [type definition](https://github.com/JuliaLang/Color.jl/blob/22ec99ea91f452e18723f6867acccdf5df990b76/src/colorspaces.jl#L78) it seems it should be between 0 and 360. @jiahao, these are your tests, can you check this out?

**Comment by timholy** [comment]
Perhaps useful for cross-checking: http://colormine.org/color-converter

**Comment by rickhg12hs** [comment]
[Some anecdotal evidence](http://stackoverflow.com/questions/30697797/converting-images-from-rgb-to-hsl-and-back-again-with-julia) from StackOverflow that this fix may be adequate.

**Comment by timholy** [comment]
I'm going to merge this, but @jiahao, can you please look at those tests again with respect to the issue I raised above?

**Comment by dcjones** [comment]
I suspect that those tests are correct but we're just testing a very narrow range of hue values.

**Comment by timholy** [comment]
I'm a little concerned, though, given that prior to this commit we were testing that the algorithm gave **incorrect** values.

**Comment by jiahao** [comment]
@timholy sorry, just got back from a few weeks' travel.

The tests I added were only confirming behavior that was present 8 months ago, back when I wanted to make sure that the vector space addition operation was correct. I had asked for help in asserting correctness, but nothing transpired of those. So I'm happy that people are working through the tests and checking them.

**Comment by timholy** [comment]
Thanks, @jiahao. I'm no color-space guru myself, so I hope some of the other folks who know this stuff chime in eventually.

**Pull request merged**
